### ISSUE TITLE
Error de diseño Banderas

### ISSUE THREAD

**Issue by Stevie1175** [La-Brujula/front#162]
**Descripción del error**
Al ver la barra de búsqueda, aparecen las abreviaciones "MX", "CO" y "AR" en lugar de las banderas de los países. Adicional a esto, más abajo, en la sección debajo de los PDFs de La Brújula, aparecen igual las abreviaciones "MX" y "CO" sin las banderas en el navegador de Chrome. En Firefox salen las banderas con un diseño caricaturesco y ya en Safari sí aparecen como emojis.

También se ve extraña la caja blanca donde se encuentra el texto/bandera, tal vez sería buena opción cambiarla por una caja transparente (o del color de la barra) con un contorno blanco, al igual que la barra de búsqueda.

**Pasos para reproducir**
1. Desplazarse a 'la barra de búsqueda'
2. Hacer click en 'MX o la bandera de México'

**Comportamiento esperado**
Deberían aparecer las banderas de los países en vez del texto de abreviación. Esto debería funcionar en todos los navegadores, no solo en Safari.

**Screenshots**
Chrome 1:
![Chrome 1](https://github.com/user-attachments/assets/80342c23-8e0b-4d75-bde0-bdd1344338c9)
Chrome 2:
![Chrome 2](https://github.com/user-attachments/assets/22210c7d-dea8-474b-aa7d-76e6719d6ce8)
Safari 1:
![Safari 1](https://github.com/user-attachments/assets/7ddd82fa-5b3c-47af-be24-05deecbd6596)
Safari 2:
![Safari 2](https://github.com/user-attachments/assets/0d423838-50e3-4102-8158-b320ef63a5e3)
Firefox 1
![Firefox 1](https://github.com/user-attachments/assets/f592c9e1-6e45-4689-8af4-215ddfe78748)
Firefox 2:
![Firefox 2](https://github.com/user-attachments/assets/f79268e4-4617-4734-8f5f-4aba99b7c9e9)

**Información adicional:**
 - Tipo de dispositivo: Computadora
 - Navegador: Google Chrome, Firefox y Safari
 - Cuando se arregle se debe avisar a: Stevie1175

**Comment by Levario0155** [comment]
Sigue sin resolverse este problema para dispositivos windows.

![image](https://github.com/user-attachments/assets/6e20b619-af16-4506-ac9e-62fbb847a870)
