### ISSUE TITLE
Verificación de correo con error

### ISSUE THREAD

**Issue by Levario0155** [La-Brujula/front#175]
**Descripción del error**
Al momento de verificar el correo se presenta una página de error.

**Pasos para reproducir**
Qué pasos debo seguir para llegar al error:
1. Ir a bandeja de entrada del correo que se utilice
2. Hacer click en Verificar correo

**Comportamiento esperado**
Debería no presentarse ningún error y verificarse el correo. La cuestión es que el correo sí se verifica, pero la inicio aparece un mensaje de error que confunde a los usuarios. Y nos podemos estarle explicando a todos que deben ir al inicio, luego refrescar la página y hacer un combo de street fighter para que les aparezca el mensaje correcto.

**Screenshots**
![image](https://github.com/user-attachments/assets/6973c353-4aa3-461c-bd7d-ed5ba4915158)

**Información adicional:**
 - Tipo de dispositivo: Computadora
 - Navegador: Chrome & Safari
 - Cuando se arregle se debe avisar a: Levario0155

**Comment by Dpalme** [comment]
ya se encuentra desplegada una nueva versión en [la versión interna de la página](staging.labrujula.com) donde se elimina este error. Falta definir si se realiza el esfuerzo por desplegar esto por aparte en la versión pública de la página o si saldrá junto con el módulo de bolsa de trabajo
