### ISSUE TITLE
Cambiar el nombre del area "crew" a "equipo humano"

### ISSUE THREAD

**Issue by Dpalme** [La-Brujula/front#18]
Cambiar el nombre para el área que ahora es "Crew" a "Equipo Humano"

**Comment by Dannnnn-afk** [comment]
Voy a cambiar el nombre principla del área por ahora pero estoy viendo que en "referentes" hay muchisimos "crew" por ingles, lo dejo asi o los cambio todos?

**Comment by Dpalme** [comment]
> Voy a cambiar el nombre principal del área por ahora pero estoy viendo que en "referentes" hay muchisimos "crew" por ingles, lo dejo asi o los cambio todos?

Gracias Dani, sólo ahí. Es más un tema de experiencia de usuario que de funcionamiento. Raúl quedó de revisar la matriz (otra vez) para ajustar las referencias.
