### ISSUE TITLE
[IDEA] Compress images before uploading

### ISSUE THREAD

**Issue by Dpalme** [La-Brujula/front#26]
**Describe the solution you'd like**
Using [compress.js](https://thewebdev.info/2020/09/05/compress-images-before-uploading-to-a-server-with-the-compress-js-library/) we pre-process images to reduce their size and save on storage.

**Describe alternatives you've considered**
Server-side compression would be ideal but as it stands it's proven more difficult than expected

**Comment by Dannnnn-afk** [comment]
Los logos si no mal recuerdo ya estan comprimidos, pero pues lo hago con todas las imagenes que tengamos no?

**Comment by Dpalme** [comment]
nel flaco, me refería más a las fotos de perfil cuando las suben los usuarios. para ahorrar en espacio lo más posible
